---
# Source: bankflow-http-api/templates/workload.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: payments-api-selfservice
  namespace: dev
  labels:
    app.kubernetes.io/name: payments-api-selfservice
    bankflow.io/owner: "payments-team"
    bankflow.io/environment: "dev"

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: payments-api-selfservice
---
# Source: bankflow-http-api/templates/workload.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api-selfservice
  namespace: dev
  labels:
    app.kubernetes.io/name: payments-api-selfservice
    bankflow.io/owner: "payments-team"
    bankflow.io/environment: "dev"
automountServiceAccountToken: false
---
# Source: bankflow-http-api/templates/workload.yaml
apiVersion: v1
kind: Service
metadata:
  name: payments-api-selfservice
  namespace: dev
  labels:
    app.kubernetes.io/name: payments-api-selfservice
    bankflow.io/owner: "payments-team"
    bankflow.io/environment: "dev"

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: payments-api-selfservice

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
# Source: bankflow-http-api/templates/workload.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api-selfservice
  namespace: dev
  labels:
    app.kubernetes.io/name: payments-api-selfservice
    bankflow.io/owner: "payments-team"
    bankflow.io/environment: "dev"
    bankflow.io/channel: "stable"
  annotations:
    bankflow.io/golden-path: "http-api"
    bankflow.io/golden-path-version: "1.1.0"

spec:


  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: payments-api-selfservice

  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments-api-selfservice
        bankflow.io/owner: "payments-team"
        bankflow.io/environment: "dev"
        bankflow.io/channel: "stable"

    spec:
      serviceAccountName: payments-api-selfservice
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: payments-api-selfservice
          image: "bankflow/payments-api:1.0.0"
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:
            - name: APP_VERSION
              value: "1.0.0"

            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PLATFORM_CHANNEL
              value: "stable"
            - name: PILOT_MODE
              value: "false"

          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: temporary-files
              mountPath: /tmp

      volumes:
        - name: temporary-files
          emptyDir: {}
---
# Source: bankflow-http-api/templates/workload.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: payments-api-selfservice
  namespace: dev
  labels:
    app.kubernetes.io/name: payments-api-selfservice
    bankflow.io/owner: "payments-team"
    bankflow.io/environment: "dev"

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payments-api-selfservice

  minReplicas: 2
  maxReplicas: 3

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
